### ISSUE TITLE
Opencv grabber problem

### ISSUE THREAD

**Issue by SimoneErcoli** [bytedeco/procamcalib#12]
I am trying to use your procamcalib software (Mac os X build). I have some problem with the framegrabber. The application starts and the camera image "flash" but after 30/40 seconds I have this error       

java.lang.RuntimeException: Unknown exception.
at org.bytedeco.javacpp.opencv_videoio$VideoCapture.read(Native Method)

at org.bytedeco.javacv.OpenCVFrameGrabber.trigger(OpenCVFrameGrabber.java:232)

I am using opencv grabber because I have a "load class error" trying to use the other grabbers

**Comment by saudet** [comment]
Yes, OpenCV doesn't work very well on Mac OS X. FFmpeg works better usually:
https://trac.ffmpeg.org/wiki/Capture/Webcam
According to that site, if we set the format to "avfoundation" and specify an empty string or "default" for the device filename or path it should work.

**Comment by SimoneErcoli** [comment]
I have to recompile the project ?

**Comment by saudet** [comment]
No, it should work with the current set of binaries just fine. Choose "FFmpeg" as your "FrameGrabber".

**Comment by SimoneErcoli** [comment]
what about deviceFile and devicePath ???

**Comment by saudet** [comment]
See the comment above.

**Comment by SimoneErcoli** [comment]
![cam](https://user-images.githubusercontent.com/5557835/31608204-cdeaccb0-b26f-11e7-868d-73bba22cb172.png)

how to use this information to fill the camera path ??

**Comment by saudet** [comment]
Well, according to https://trac.ffmpeg.org/wiki/Capture/Webcam#AVFoundation
we can use the device number as "filename"...

**Comment by SimoneErcoli** [comment]
ok...using terminal works but i don't understand where I have to put this value in your interface

**Comment by saudet** [comment]
Like you said, in "devicePath"...

**Comment by SimoneErcoli** [comment]
<img width="967" alt="error" src="https://user-images.githubusercontent.com/5557835/31612974-f6645726-b281-11e7-9fde-392ba24901ff.png">

same error also with the name of the camera

**Comment by saudet** [comment]
What did you use for the "format" field?

**Comment by SimoneErcoli** [comment]
nothing

**Comment by SimoneErcoli** [comment]
solved ;-) ...I have just to find the right dimension and frame rate...but now I am able to open the webcam e try to match the two boards

**Comment by saudet** [comment]
Good! Setting the format to "avfoundation" as I mentioned above would probably help as well.
