### ISSUE TITLE
Save the captured images and feed them to calibration

### ISSUE THREAD

**Issue by andrewsunst** [bytedeco/procamcalib#18]
I am trying to do some comparison and I need to take photos of the same positions. Since the procamcalib grab the frames from realsense and convert it into iplimages to do the calibration, I tried the methods cvsaveimage and imwrite (which is in the document of javacv) method but they will crash the jre with the core dump error. Would you offer some help about how to save the captured images and later feed them back to the procamcalib to do the calibration?

**Comment by saudet** [comment]
Probably easier to just capture a video file. Check the sample code in the
README.md file of JavaCV:
https://github.com/bytedeco/javacv
