### ISSUE TITLE
Unable to project or get Camera settings

### ISSUE THREAD

**Issue by nikhil4595** [bytedeco/procamcalib#21]
Hi @saudet 

I have connected a DLP Lightcrafter and Imaging Source Machine Camera to perform calibration of the system. Unfortunately, everytime I try to run the calibration with entered parameters, the Camera 0  and the projector 0 window shows nothing(plain white and black respectively).
Is there anything that I might be missing or haven't configured correctly. Thank you so much.

Regards,
Nikhil

**Comment by saudet** [comment]
What kind of parameters? Does it work with a webcam? Also, if you try to use the monitor as output, do you see the pattern displayed?

**Comment by nikhil4595** [comment]
parameters like frameRate, image height,width. It does not work with a webcam either(also running with OpenCv as frame grabber) . I tried using the monitor as output , still getting a black screen on the Projector window

**Comment by saudet** [comment]
What do you mean by "not working" with a webcam?

**Comment by nikhil4595** [comment]
I figured that out, my system webcamera was defect, and not recognized even with the device manager. So the camera works if I disable it. Thanks a lot.
Is there any solution for the resolution issue , because 640x480 does not cover the whole scene in the case of my setup and the markers are not detected for 1024*768 or higher resolutions.

**Comment by saudet** [comment]
You can try to set the resolution with the "imageWidth" and "imageHeight" parameters.

**Comment by nikhil4595** [comment]
I already tried that , bot for VideoInput and OpenCV with 1024x768 and 1920x1080. 
A couple of times it logged complete error file, but mostly , every other time it flips the stream/image both horizontally and vertically.

**Comment by saudet** [comment]
If you can't change it that way, it probably means there is some other way usually some tool that you need to use to change the resolution of your camera.
