### ISSUE TITLE
Using calibration data with OpenCV

### ISSUE THREAD

**Issue by zekeadam** [bytedeco/procamcalib#22]
Hello,

I'm a bit confused about how to use the resulting values with OpenCV and cant find too much information on the topic. Could you give me some pointers about how to align the cameras image the projectors image using OpenCV? I was experimenting with cv.undistort() and a few other functions but can't figure it out.

Thanks in advance, great software!

**Comment by saudet** [comment]
There is code that does that as part of JavaCV and ProCamTracker, check it out!

**Comment by saudet** [comment]
If you have any questions about them, please feel free to ask here.

**Comment by zekeadam** [comment]
Thank you for the help!
Do I get it right that the `undistort(double[] xd, double[] k)` function undistorts the cameras image then the `distort(double[] xu, double[] k)` (in  javacv/ProjectiveDevice.java) distorts it so its aligned to the projector?

**Comment by saudet** [comment]
Yes, that's the idea, but those methods are for individual points.
