### ISSUE TITLE
Program is stuck at "calibrating..."

### ISSUE THREAD

**Issue by limiy1** [bytedeco/procamcalib#3]
Dear Samuel,

I read your article and I would like to use your procamcalib program to calibrate a projector. I successfully got all images with version 1.1 (binary) but the program is stuck at "calibrating..." state. Do you have an idea of this problem, please?

Thank you in advance for your help!

Best regards,
Liming

**Comment by limiy1** [comment]
Well, it works now... The problem comes from colorcalibratoin, when it is disabled, the program works fine. Thank you for the library! Very easy to use!

**Comment by saudet** [comment]
Good :+1:  Thanks
